### PR TITLE
Finished Project!

### PR DESCRIPTION
**Pull request by K-MYR**
Thanks for reviewing my project! Have a great day!

### CODE REVIEW

**Comment by K-MYR** [comment]
I found some  mistakes i made, so please wait for my final commit called "final commit" before merging! Thank you!

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@K-MYR Thanks for submitting! I'm getting this error when trying to update a record: 
image

**Comment by K-MYR** [comment]
@TheCSharpAcademy My bad, i forgot to check after i made some little changes 🙃! Everything works fine again! Thank you!

**Comment by TheCSharpAcademy** [comment]
@K-MYR Well done! You're now an Olive Green Belt 😁 I couldn't find you on Discord with the alias you provided 🥺

**Comment by K-MYR** [comment]
> @K-MYR Well done! You're now an Olive Green Belt 😁 I couldn't find you on Discord with the alias you provided 🥺

thahts weird :/ i wrote a message into the discord channel " introduce -yourself": https://discord.com/channels/925901888203935744/925902214747263026/1161262374511194194 
you replied "I'm slowly trying to work with python myself
so hard to find time to learn another language though"....so that account is  is me ^^

One Question regarding my CodingTracker Project: you approved it but did not merge it? are not all projects gettin merged or should i open another pull request?

**Pull request merged**
