### PR TITLE
Finished HabitTracker

### PR DESCRIPTION
**Pull request by jakubecm**
It is done, working and two out of three challenges completed.
I could have done the third one as well, but I am just excited to start the next one, so I left the third challenge out.
I also hope I didnt break anything in my project, because originally I developed it in my own repository [here ](https://github.com/jakubecm/HabitTracker), and I could not add that here since that would be adding a repo into another repo, so I kind of worked around it by deleting .git folder of the copy before sending it here. But it should be fine. I think haha.

### CODE REVIEW

**Comment by jakubecm** [comment]
Okay so I refactored it as it was mentioned in the PR I mentioned earlier, it should be compliant with it now. What is missing is some user input sanitation for when the user is creating a new habit for example, so they dont enter empty strings etc. It also struck my mind that now I need to check for duplicate habits, will solve it asap.

**Comment by jakubecm** [comment]
Okay, everything should be fine now.

**Comment by Jinboi** [comment]
@jakubecm 

Hi jakubecm!

Happy Friday! Hahaha

I think there are some issues with the codes you uploaded. Can you please fix the issue and re-submit? Thank you! 😄

Please see below:

Please fix the errors picked up by code analysis before I review your code. You can find instructions in item 6 of this article: https://www.thecsharpacademy.com/article/52/code-reviews. If you have any questions feel free to reply to this comment or reach out on Discord via the #codeReview channel

**Comment by jakubecm** [comment]
No issues with the code. The static analysis has a problem with the README file.

**Comment by Jinboi** [comment]
yes my apologies, jakubecm, I must've missed the memo. I'll go ahead and review your codes shortly. Sorry about that!

**Comment by Jinboi** [comment]
Hi jakubecm!

Everything looks great! 😄 
I'll mark it approved and please move on to the next project! Thank you!

**Pull request closed without merging**
