### PR TITLE
Submitting HabitTracker project 

### PR DESCRIPTION
**Pull request by GitNach**

### CODE REVIEW

**Comment by GitNach** [comment]
Cleaned and fixed everything

**Comment by stevietv** [comment]
Hi @GitNach - thanks for your submission. I've taken a look over it and right now there are a couple of things that are missing to approve it:

* the Quantity on the habit can be updated, updating records is a project requirement
* there is no ReadMe - this is a project requirement
* I would also like to know why you have gone with Forms input when this is a console project

**Comment by GitNach** [comment]
Hey, how are you?

-I’ll add the update and the ReadMe in the next couple of days.

-I find it more fun by making an UI, in the project there’s the option to use MAUI, but i’ve choosen to use WinForms for now because it’s pretty easy and straightforward.

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Stevie Robinson ***@***.***>
Enviado: Saturday, June 22, 2024 4:17:48 PM
Para: TheCSharpAcademy/CodeReviews.Console.HabitTracker ***@***.***>
Cc: Ignacio Kertesz ***@***.***>; Mention ***@***.***>
Asunto: Re: [TheCSharpAcademy/CodeReviews.Console.HabitTracker] Submitting HabitTracker project (PR #149)


Hi @GitNach<https://github.com/GitNach> - thanks for your submission. I've taken a look over it and right now there are a couple of things that are missing to approve it:

  *   the Quantity on the habit can be updated, updating records is a project requirement
  *   there is no ReadMe - this is a project requirement
  *   I would also like to know why you have gone with Forms input when this is a console project

**Comment by GitNach** [comment]
Hi @stevietv - I've added the ReadMe file and added the update functionality

**Comment by GitNach** [comment]
Hi @stevietv -I've added the ReadMe and the update functionality

**Comment by stevietv** [comment]
hi @GitNach - the only issue that seems to remain is the missing `using System.ComponentModel;` in Habit.cs - without it the [Browsable]  attribute causes a compile error. Can you fix that up?

**Comment by GitNach** [comment]
Hi @stevietv -I've fixed it. I did removed it at first because the static code analysis was giving an error, so i made the using global and it went away.

**Comment by stevietv** [comment]
great, then this is approved! ✅

**Pull request closed without merging**
