### PR TITLE
Finished this time I think :)

### PR DESCRIPTION
**Pull request by Mattias1610**

### CODE REVIEW

**Comment by chrisjamiecarter** [comment]
@Mattias1610,

Actually, as I am already assigned on the stale one. Would you like me to just review this pull request and pretend it is for the already submitted one?

That way you do not have to do anything.

Let me know what you decide to do.

Thanks,
@chrisjamiecarter

**Comment by Mattias1610** [comment]
Yeah, review this one please

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @Mattias1610 👋 

Great job on another application submitted 🎉 

I have added some minor review comments to help support your growth as a developer.

Unfortunately I cannot currently pull down your code to test. I think that is due to you deciding to put a `:` in your directory name.

image

As per the [code-reviews](https://thecsharpacademy.com/article/52/code-reviews) page, could you rename your directory to HabitTracker.Mattias1610?

image

And also ensure that all your files are children of this directory?

image

That should then allow me to progress and get your project marked as completed!

Thanks,
@chrisjamiecarter

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @Mattias1610 👋 ,

I am testing you application and have found a bug.

When I attempt to update a record an exception is thrown:
image

This currently fails two requirements:
- [ ] The users should be able to insert, delete, update and view their logged habit.
- [ ] You should handle all possible errors so that the application never crashes.

Please could you investigate and resolve?

Again, commit and push your code once fixed and I will continue my review.

Let me know if you need any help/support.

Thanks,
@chrisjamiecarter

**Comment by Mattias1610** [comment]
I m having some trouble with the parameter function , and I think my laptop is at fault so I "stepped over that", sorry

**Comment by chrisjamiecarter** [comment]
@Mattias1610 - I will mark as completed.

Not the easier program to use, mainly as the date format you request the user to enter will never work with your try parse exact format (DD/MM/YY != dd-MM-yy). The symbols kind of need to be the same.

image

**Pull request closed without merging**
