### PR TITLE
Request for Code Review of Habit Tracker App #2

### PR DESCRIPTION
**Pull request by NathanJenner**
Fixed bug where pressing 1 caused the app to close. 

Fixed bug where pressing >6 or any alpha char caused the app to close.

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@Jinboi I think this one is yours, another PR was created from this one: https://github.com/TheCSharpAcademy/CodeReviews.Console.HabitTracker/pull/171

Any updates? 😁

**Comment by NathanJenner** [comment]
Hi,

Yeah I updated it and submitted another PR-

https://github.com/TheCSharpAcademy/CodeReviews.Console.HabitTracker/pull/174






Steadfast Group acknowledges the Traditional Owners of the land where we work and live.
We pay our respects to Elders past and present.

IMPORTANT - CONFIDENTIALITY AND PRIVILEGE NOTICE. This e-mail is only to be used by the addressee. It is confidential and may contain legally privileged information. If you are not the intended recipient, any use (including disclosure by either copying or forwarding of this e-mail or any attachment) is strictly prohibited. Confidentiality and any legal privilege are not lost by reason of the mistaken delivery to you. If you have received this e-mail in error, please delete it and notify us immediately by e-mail or telephone. Please consider the environment before printing this email. Thank you.

**Comment by Jinboi** [comment]
Didn't know there was this PR. I'll get to it as soon as I can.

**Comment by Jinboi** [comment]
image
image


I've tried to create a 'TEST' habit and view it but it wouldn't show. Can you look into this please?

**Comment by TheCSharpAcademy** [comment]
@Jinboi don't forget to assign yourself 😁

**Comment by Jinboi** [comment]
image
I can't assign myself :(

**Comment by TheCSharpAcademy** [comment]
@Jinboi Added you to the repo

**Comment by NathanJenner** [comment]
@Jinboi  - i've now corrected the issue of nothing appearing when trying to view the habit. Can you please review again.
thanks.

**Comment by Jinboi** [comment]
Thanks for the invitation—Assigned myself just now.  I'll get to it and review this as soon as I can. Thank you!

**Comment by Jinboi** [comment]
image
I've updated Drink count to 500 but it doesn't get reflected

image

I've created a new habit called coding and updated it to 200 but it doesn't show.

Please look into this when you can. Thank you! 

-Youngwoo

**Comment by Jinboi** [comment]
@NathanJenner 

Yeah—please ping me using @ when you're project is ready to be reviewed. Thank you!

**Comment by TheCSharpAcademy** [comment]
@Jinboi looks like it's been updated 😁

**Comment by NathanJenner** [comment]
@Jinboi  - i think i've got it all sorted now. Can you please review. Thanks.

**Comment by Jinboi** [comment]
@NathanJenner ,

Thank you for fixing the bug and submiting your project again. 

The project looks excellent, and I'll mark it as completed. Please move on to the next project!

I do have a minor suggestion: I noticed that you declared a var connectionString but only used it once. In other methods, you continued to hardcode "Data Source=habits.db". It might be more efficient to refactor the code and consistently use the connectionString variable. That way, if you ever need to change the database name from "habits.db" to something else, you can simply update it in one place rather than across multiple methods.

But again, it's just a minor suggestion, not a major one, for your future reference in your projects going forward.

Thank you again and happy coding! 

image

 var connectionString = "Data Source=habits.db;";

**Comment by TheCSharpAcademy** [comment]
@NathanJenner Congratulations! You got your green belt!! 🫒🫒
AplausosClappedGIF

If possible join our Discord Community and add your username [to your profile](https://thecsharpacademy.com/dashboard/profile) so you can be part of the community as well. 😁

**Pull request closed without merging**
