### PR TITLE
my first commit for runner habit tracker

### PR DESCRIPTION
**Pull request by Mohamed-AbdElhamed99**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Mohamed-AbdElhamed99 Thanks for submitting! It's looking good but I'm getting this when trying to view records:

image

image


This is because dates can differ depending on the culture in .NET. Trying using the DateTime.TryParseExact() method for parsing the date, you'll need to provide the EXACT string that you expect the user to input. Make sure to tell the user what's the EXACT expected format.  Let me know if you have any questions. 🤓

**Comment by Mohamed-AbdElhamed99** [comment]
@TheCSharpAcademy  Thank you for reviewing 
I edit my code and used TryParseExact and specify the exactly date format i want user to enter and it works well.

I have question about database SQLite 
301691393-57f348ba-d003-487b-a3d3-4b9548e0993f

How i can see the database and tables i created i am using vs but i didn't see any tool like this 
i want to know what is this GUI tool for database

**Comment by TheCSharpAcademy** [comment]
> @TheCSharpAcademy Thank you for reviewing I edit my code and used TryParseExact and specify the exactly date format i want user to enter and it works well.
> 
> I have question about database SQLite 301691393-57f348ba-d003-487b-a3d3-4b9548e0993f
> 
> How i can see the database and tables i created i am using vs but i didn't see any tool like this i want to know what is this GUI tool for database

Yeah I use Db Browser https://sqlitebrowser.org/ see if it works for you?

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Mohamed-AbdElhamed99 Don't forget you need to commit and push your new code so I can review it. 🤓

**Comment by Mohamed-AbdElhamed99** [comment]
@TheCSharpAcademy Sorry i was thought i push it i commit it but forget to push
now i commit again and git "said nothing to commit, working tree clean"
So I push again

**Review by Doc415 — CHANGES_REQUESTED** [review]
Hi there i reviewed your code and there are some points to reevaluate.
View all records function returns empty
image
When i try to insert a record, date format was prompted as dd-mm-yy
when i enter 11-11-22 the validation does not pass and it requires another format
Can you check these parts of the code again please?

**Comment by Mohamed-AbdElhamed99** [comment]
@Doc415  Thanks for reviewing my project 
I have checked the problems you noticed and it all worked with me so i commit again and pushed the project

**Review by Doc415 — COMMENTED** [review]
Hey Muhamed. The View all selection still doesnt work and the program throws invalid date exception.
Can you please check if the seed data dates are valid datetimes?

image

**Review by Doc415 — CHANGES_REQUESTED** [review]
View all records selection throws invaild date exception. Please check seed data datetimes if they are valid<

**Comment by Mohamed-AbdElhamed99** [comment]
Hello @Doc415 thanks for your review 
I decided to make new project habit tracker to be similar to coding tracker i made and has been approved ,
there are more features here i added in this project like Spectre.Console

**Review by Doc415 — CHANGES_REQUESTED** [review]
Hey Muhamed it looks much better and all functioning. 
There is just a need of valitaion review.
When i am inserting a new record, i enter 0 or -1 to running time and program records it .
User should be warned that it is not valid and should enter a positive number. After the fix we can merge your project.

image

**Comment by Mohamed-AbdElhamed99** [comment]
@Doc415 Thank you for reviewing 
I added validation function to just allow positive integers for kilometers.

**Review by Doc415 — APPROVED** [review]
Good work. Thanks for your collaboration.

**Pull request merged**
