### PR TITLE
Committing finished project

### PR DESCRIPTION
**Pull request by jkjones98**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@jkjones98 Hey there! Thanks for submitting! You're close.
At the moment I can't delete records, when I press option 3, nothing happens.
This is a minor issue but I'll get more strict in the future: Refrain from pushing comments unless absolutely necessary. Code should be self-explanatory.

image

**Comment by TheCSharpAcademy** [comment]
@jkjones98 Let me know if you need help 😊

**Comment by jkjones98** [comment]
> @jkjones98 Hey there! Thanks for submitting! You're close. At the moment I can't delete records, when I press option 3, nothing happens. This is a minor issue but I'll get more strict in the future: Refrain from pushing comments unless absolutely necessary. Code should be self-explanatory.
> 
> image

Hi 

> @jkjones98 Let me know if you need help 😊

Hi, Sorry! Had a busy couple of days with work being done in the house and I've been working on the MAUI version of the habit tracker, once I'm done with that I'll have a look at and fix the delete option not working! Thank you for the feedback I really appreciate it

As for the comments, I usually only put those in to act as notes and help solidify my understanding of any new functions, I'll make sure to remove them and add them into a word doc for myself in the future though thank you:)

**Comment by TheCSharpAcademy** [comment]
@jkjones98 YEah that's actually a good thing. What I suggest is that you have your own repositories in your Github with comments as you need, but when pushing code, only leave the ones that are absolutely necessary for other people. The reason being I want to simulate a real-world environment where you'll be punished for doing PRs with unnecessary comments. 😆

**Review by jkjones98 — COMMENTED** [review]
Changes made to get delete function working, I made a call to the ViewAllMethod in ViewAllRecords Class instead of DisplayRecs method in AllRecords class(This will be a lesson in learning to name things better!) Also removed comments

**Comment by TheCSharpAcademy** [comment]
@jkjones98 Thanks for the changes. Project approved 😁

**Pull request merged**
