### PR TITLE
I think it is done

### PR DESCRIPTION
**Pull request by Mattias1610**

### CODE REVIEW

**Review by Mattias1610 — COMMENTED** [review]
Finished

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @Mattias1610 ,

Before I review you project, you must ensure you have met all the requirements!

Please review:

- [ ] Your project needs to contain a Read Me file where you'll explain how your app works.

Once you have fulfilled this requirement, please **Commit** and **Push** your changes, and I will continue my review.

Also, one quick thing I noticed:

**Solution Structure**
One small mistake with your submission directories, it should be ProjectName - dot - GitHubUserName:

```
// Current.
.
└── Mattias.Habit-tracker/
    └── *

// Correct.
.
└── HabitTracker.Mattias1610/
    └── *
```

Thanks
@chrisjamiecarter

**Comment by chrisjamiecarter** [comment]
Hey @Mattias1610 ,

Did you mean to close this Pull Request? All you had to do was push a README.md file...

Thanks
@chrisjamiecarter

**Comment by TheCSharpAcademy** [comment]
@chrisjamiecarter We'll archive after two weeks of the requested changes if the ticket is left unattended. You'll still get the review points 👌🏻

@Mattias1610 Let us know if we can help you complete the project 😄

**Comment by Mattias1610** [comment]
Yeah I meant to close it cause I m not really familiar with the git push and all of the options so I decided to close this request and create another one with the readme file, it seemed easier, sorry if it created discomfort.

**Pull request closed without merging**
