### PR TITLE
Project Finished!

### PR DESCRIPTION
**Pull request by jsnprojs**
Thank you for reviewing!

### CODE REVIEW

**Comment by stevietv** [comment]
Hi @jsnprojs - currently the program is failing in the `GenerateRandomData()` Method:

```
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at habit_tracker.Program.GenerateRandomData() in E:\Development\study\CSharpAcademy\CodeReviews.Console.HabitTracker\HabitLogger\HabitLogger\Program.cs:line 119
   at habit_tracker.Program.Main(String[] args) in E:\Development\study\CSharpAcademy\CodeReviews.Console.HabitTracker\HabitLogger\HabitLogger\Program.cs:line 43
```

Its because your trying to insert random records with a random habit ID between 1 and 4, meanwhile the database isn't seeded with any default habits. Could you take a look at fixing that up so that I can review?

**Comment by jsnprojs** [comment]
Thank you, it should now generate random data correctly.

I did remember to put my GitHub name after project name for the first two projects, but forgot about this one sorry.

**Comment by stevietv** [comment]
hi @jsnprojs - Great work, thanks for updating it. Nice job on tackling some of the challenges also!

All in all its working, however there is one requirement that you haven't yet met: 

* `Your project needs to contain a Read Me file where you'll explain how your app works.`

Writing readme's for your programs is an important part of development, could you take care of this requirement?
I also noticed that your seeded data gets the format `dd-mm-yyyy` whereas the user is required to enter it as `dd-mm-yy` - this wouldn't be a reason for not approving, but its just a hint from me from a user perspective.

**Comment by jsnprojs** [comment]
Fixed, thank you for reviewing!

**Comment by stevietv** [comment]
thanks
Approved ✅

**Pull request closed without merging**
