### PR TITLE
Pull request for the Habit Tracker Project.

### PR DESCRIPTION
**Pull request by Aditya-083**

### CODE REVIEW

**Comment by Aditya-083** [comment]
Please review my submission for the Habit Tracker Project. Add suggest any improvements . Thanks

**Comment by antonderegt** [comment]
> Please review my submission for the Habit Tracker Project and suggest any improvements . Thanks

Did you submit the project on the academy website?

**Comment by antonderegt** [comment]
@Aditya-083 after you created the pull request successfully, like you did, you need to submit it on the project page. 

1. Copy the url of this PR
2. Go to the academy site and find the page for this project
3. Scroll down to find the submit button 
4. Enter the url you just copied

This way reviewers will be notified of a project to review. And you will be able to get the points.

Hope this helps, let me know! Happy to help if you have further questions!

**Comment by Aditya-083** [comment]
@antonderegt Thank you very much

**Review by antonderegt — CHANGES_REQUESTED** [review]
Hey @Aditya-083, now you submitted it correctly, I can see it in the review portal! You did a good job. I like that you included images in your README and you're preventing SQL injection with the parameterised queries!

There are two small things I want to ask you to update. The app allows to enter negative numbers. Or did you add this as a feature to also track you peeing habit at the same time? 😆 
And a small thing, but mandatory for your project to be approved, please have a look at the [Code Conventions](https://thecsharpacademy.com/article/58). Especially the Spacing. I saw some files start with empty lines.

If you update those two things, I'll gladly approve your project. Sorry you had to wait a month for it to be review 😄

**Comment by antonderegt** [comment]
@Aditya-083 I forgot to mention this: please click the ask for review button or mention me in a comment on this PR. Then I'll be notified and can help you as soon as possible.

**Comment by TheCSharpAcademy** [comment]
@Aditya-083 Let us know if you need help 🤓

**Comment by Aditya-083** [comment]
@antonderegt I have made the required changes can you pls check

**Review by antonderegt — APPROVED** [review]
Very nice! Thanks for the changes. I'm going to approve it. Enjoy the other projects!

**Pull request closed without merging**
