### PR TITLE
Completed the Habit Tracker Requirements and Included the Challenges

### PR DESCRIPTION
**Pull request by ukpagrace**

### CODE REVIEW

**Comment by Jinboi** [comment]
@ukpagrace 

Hi ukpagrace!

Happy Friday! Hahaha

I think there are some issues with the codes you uploaded. Can you please fix the issue and re-submit? Thank you! 😄

Please see below:

Please fix the errors picked up by code analysis before I review your code. You can find instructions in item 6 of this article: https://www.thecsharpacademy.com/article/52/code-reviews. If you have any questions feel free to reply to this comment or reach out on Discord via the #codeReview channel

**Comment by Jinboi** [comment]
My apologies, ukpagrace, I must've missed the memo about the read.me issue on this. For the future reference, you don't need to worry about that.

I'll go ahead and review your codes shortly. Sorry about that!

**Comment by ukpagrace** [comment]
> My apologies, ukpagrace, I must've missed the memo about the read.me issue on this. For the future reference, you don't need to worry about that.
> 
> I'll go ahead and review your codes shortly. Sorry about that!

okay

**Comment by Jinboi** [comment]
Everything looks great! 😄 

I'll mark it approved and please move on to the next proejct! Thank you!

**Pull request closed without merging**
