### PR TITLE
Finished project.

### PR DESCRIPTION
**Pull request by eddyfadeev**
Hi, just finished a project, thank you for your review!

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
Hey there! Thanks for submitting! Very nice project as far as I can see. I got stuck in trying to Add a new record though. What am I doing wrong?

image

**Comment by eddyfadeev** [comment]
> Hey there! Thanks for submitting! Very nice project as far as I can see. I got stuck in trying to Add a new record though. What am I doing wrong?
> 
> image

Hi, thank you for your reply. My bad, I forgot to add a help intro/submenu :)

**Review by eddyfadeev — COMMENTED** [review]
Added help menu with clarifications

**Comment by TheCSharpAcademy** [comment]
@eddyfadeev Well done sir! I think it's the first time I see anyone using partial classes around here 🤓

**Comment by eddyfadeev** [comment]
> @eddyfadeev Well done sir! I think it's the first time I see anyone using partial classes around here 🤓

Thank you! I found it as a really nice approach to organize a code

**Pull request closed without merging**
